name: Secrets Scanning and Synk

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  secrets_scan:
    name: Secrets Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Choose the desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run secrets scanning
        run: npm run scan-secrets  # Replace with your scanning script or command

  secrets_sync:
    name: Secrets Synchronization
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Choose the desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Sync secrets with Snyk
        run: npm run sync-secrets  # Replace with your synchronization script or command
